name: Feature request
description: 建议一个对多数用户有帮助的新功能
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: scenario
    attributes:
      label: 使用场景
      description: 你遇到了什么问题？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 建议方案
      description: 希望 VoxRibbon 如何解决？
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 目前如何绕过这个问题？
